(* generated by dune *)

(** @canonical Js_of_ocaml_compiler_runtime_files.Files *)
module Files = Js_of_ocaml_compiler_runtime_files__Files

module Js_of_ocaml_compiler_runtime_files__ = struct end
[@@deprecated "this module is shadowed"]
